version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cmf_backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    container_name: cmf_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: cmf_db
    restart: always
    environment:
      POSTGRES_DB: cmfdb
      POSTGRES_USER: cmfuser
      POSTGRES_PASSWORD: cmfpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: {}
