# Generated by Django 5.1.7 on 2025-05-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_fondo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.administradora')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('valor_cuota_inicial', models.FloatField(blank=True, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='ValorCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.serie')),
            ],
            options={
                'unique_together': {('serie', 'fecha')},
            },
        ),
    ]
